### ISSUE TITLE
code block应用highlight style似乎有问题

### ISSUE THREAD

**Issue by missdeer** [b3log/lute#19]
### 描述问题

```go
luteEngine := lute.New(lute.CodeSyntaxHighlight(true, true, lineNumber, "monokai"))
html, err := luteEngine.MarkdownStr("xxx", md);
```

我看了一下，似乎是 
https://github.com/b3log/lute/blob/894d398b261b8f8ef325c53592157671ce21bb63/code_block_html_renderer.go#L37 
https://github.com/b3log/lute/blob/894d398b261b8f8ef325c53592157671ce21bb63/code_block_html_renderer.go#L83
https://github.com/b3log/lute/blob/894d398b261b8f8ef325c53592157671ce21bb63/code_block_html_renderer.go#L106
这些地方style要设置到`<code>`的父节点`<pre>`上，比如最简单大概的是这样
```html
<pre class="highlight-chroma"><code>...</code></pre>
```
然后把 https://github.com/b3log/lute/tree/master/chroma-styles 这个目录下的文件挑一个写进去就有了。

或者是我用得不对？

**Comment by 88250** [comment]
language 是编程语言，围栏代码块语法需要在 `` ``` `` 后面指定编程语言，所以 Markdown 原文需要这样写：

````markdown
```go
var i int;
```
````

Chroma 的自动探测编程语言实现得太简单了，不指定编程语言的话它猜不出来是啥语言，所以代码高亮不生效。

**Comment by 88250** [comment]
对了，可以到这里看下 https://hacpai.com/guide/markdown

**Comment by missdeer** [comment]
不是的，比如monokai是个黑色背景的，当前的实现就不会渲染出来

**Comment by 88250** [comment]
> 不是的，比如monokai是个黑色背景的，当前的实现就不会渲染出来

收到，我再看下稍后回复你。

**Comment by 88250** [comment]
已经修复，麻烦再帮忙测试一下，谢谢 🙏

**Comment by missdeer** [comment]
试了一半的style，确实可以了

**Comment by 88250** [comment]
> 试了一半的style，确实可以了

收到，后续如果还有其他问题欢迎随时提。
