### ISSUE TITLE
GFM Table rendered as h2

### ISSUE THREAD

**Issue by yuin** [b3log/lute#3]
I'm a goldmark author. @88250 , Thanks for your contribution about goldmark!
Sorry I can not read Chinese, so I report in English and a free format.

```
0
-:
```

This markdown text should be rendered as following:

```
<table>
<thead>
<tr>
<th align="right">0</th>
</tr>
</thead>
</table>
```

You can confirm this result by just typing above markdown text into this comment text are and pushing preview button.

lute renders above markdown text as :

```
<h2>0</h2>
```

P.S: I've released a new version of the goldmark with some performance improvements. It would be happy if you update a benchmark results.

**Comment by 88250** [comment]
Thanks for report this issue, I will fix it later.
The benchmark results in README.md has been updated, goldmark is faster than before 👍
