### ISSUE TITLE
行级数学公式起始 $ 后是否允许数字加入开关

### ISSUE THREAD

**Issue by linyinian** [b3log/lute#38]
如图，由于$+数字中间没加空格，导致后面图片无法解析
![image](https://user-images.githubusercontent.com/39898791/69205288-88630200-0b84-11ea-8e8c-01c7330551d4.png)
![image](https://user-images.githubusercontent.com/39898791/69205289-88630200-0b84-11ea-86f5-696ee254ab3c.png)

**Comment by linyinian** [comment]
> 这样吧，我们加个开关来控制数学公式 `$` 后是否允许数字，默认不允许。但开发者可以配置为允许，这样兼容性更好，解决之前我们在 [b3log/vditor#165](https://github.com/b3log/vditor/issues/165) 中讨论的问题，同时解决由这个问题带来潜在的其他问题。
> 
> 不好意思啊，我很少登录微信

太赞了！大概会在哪个版本生效呢？

ps：如果有其他即时通讯方式也阔以，不勉强哈哈哈

**Comment by 88250** [comment]
最快的话下午可以发布一个 Vditor 版本，慢点的话明天。

就在这里沟通就好，其他方式不是你不用就是我不用 😂

**Comment by 88250** [comment]
Lute 代码调整完毕，稍后发布 Vditor。

**Comment by linyinian** [comment]
> Lute 代码调整完毕，稍后发布 Vditor。

收到，等发布后我们更新下版本
