### ISSUE TITLE
Empty list following GFM Table makes table broken

### ISSUE THREAD

**Issue by yuin** [b3log/lute#9]
#3 seems fixed, but an another bug is introduced.

```
0
-:
-
```

this markdown text should be rendered as

```
<table>
<thead>
<tr>
<th align="right">0</th>
</tr>
</thead>
</table>
<ul>
<li></li>
</ul>
```

(try this in github comment text area)

but lute renders it as 

```
<h2>0
-:</h2>
```

**Comment by 88250** [comment]
Thanks a lot, it will be fixed later.
